// Code generated by MockGen. DO NOT EDIT.
// Source: ./cron/helpers.go
//
// Generated by this command:
//
//	mockgen -source=./cron/helpers.go -destination=./mocks/cron_helpers_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
