// Code generated by MockGen. DO NOT EDIT.
// Source: ./cron/types.go
//
// Generated by this command:
//
//	mockgen -source=./cron/types.go -destination=./mocks/cron_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	cron "cronlite/cron"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIJob is a mock of IJob interface.
type MockIJob struct {
	ctrl     *gomock.Controller
	recorder *MockIJobMockRecorder
	isgomock struct{}
}

// MockIJobMockRecorder is the mock recorder for MockIJob.
type MockIJobMockRecorder struct {
	mock *MockIJob
}

// NewMockIJob creates a new mock instance.
func NewMockIJob(ctrl *gomock.Controller) *MockIJob {
	mock := &MockIJob{ctrl: ctrl}
	mock.recorder = &MockIJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIJob) EXPECT() *MockIJobMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIJob) Delete(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIJobMockRecorder) Delete(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIJob)(nil).Delete), ctx)
}

// GetState mocks base method.
func (m *MockIJob) GetState(ctx context.Context) (*cron.JobState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", ctx)
	ret0, _ := ret[0].(*cron.JobState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *MockIJobMockRecorder) GetState(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockIJob)(nil).GetState), ctx)
}

// SaveState mocks base method.
func (m *MockIJob) SaveState(ctx context.Context, state *cron.JobState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveState indicates an expected call of SaveState.
func (mr *MockIJobMockRecorder) SaveState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockIJob)(nil).SaveState), ctx, state)
}

// Start mocks base method.
func (m *MockIJob) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockIJobMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIJob)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockIJob) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockIJobMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockIJob)(nil).Stop), ctx)
}

// MockIWorkerIdProvider is a mock of IWorkerIdProvider interface.
type MockIWorkerIdProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkerIdProviderMockRecorder
	isgomock struct{}
}

// MockIWorkerIdProviderMockRecorder is the mock recorder for MockIWorkerIdProvider.
type MockIWorkerIdProviderMockRecorder struct {
	mock *MockIWorkerIdProvider
}

// NewMockIWorkerIdProvider creates a new mock instance.
func NewMockIWorkerIdProvider(ctrl *gomock.Controller) *MockIWorkerIdProvider {
	mock := &MockIWorkerIdProvider{ctrl: ctrl}
	mock.recorder = &MockIWorkerIdProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkerIdProvider) EXPECT() *MockIWorkerIdProviderMockRecorder {
	return m.recorder
}

// Id mocks base method.
func (m *MockIWorkerIdProvider) Id() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Id indicates an expected call of Id.
func (mr *MockIWorkerIdProviderMockRecorder) Id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockIWorkerIdProvider)(nil).Id))
}
