// Code generated by MockGen. DO NOT EDIT.
// Source: ./cron/constants.go
//
// Generated by this command:
//
//	mockgen -source=./cron/constants.go -destination=./mocks/cron_constants_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
