// Code generated by MockGen. DO NOT EDIT.
// Source: ./cron/job_state.go
//
// Generated by this command:
//
//	mockgen -source=./cron/job_state.go -destination=./mocks/cron_job_state_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
